/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.TelaProdutoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author jjsco
 */
public class TelaProduto extends javax.swing.JInternalFrame {

    private final TelaProdutoController controller;
    /**
     * Creates new form TelaCliente
     */
    public TelaProduto() {
        initComponents();
        controller = new TelaProdutoController(this); 
    }

    public JTable getjTableProdutos() {
        return jTableProdutos;
    }

    public void setjTableProdutos(JTable jTableProdutos) {
        this.jTableProdutos = jTableProdutos;
    }

    public JTextField getjTextFieldNomeProduto() {
        return jTextFieldNomeProduto;
    }

    public void setjTextFieldNomeProduto(JTextField jTextFieldNomeProduto) {
        this.jTextFieldNomeProduto = jTextFieldNomeProduto;
    }

    public JTextField getjTextFieldPesquisarProd() {
        return jTextFieldPesquisarProd;
    }

    public void setjTextFieldPesquisarProd(JTextField jTextFieldPesquisarProd) {
        this.jTextFieldPesquisarProd = jTextFieldPesquisarProd;
    }

    public JTextField getjTextFieldPrecoProduto() {
        return jTextFieldPrecoProduto;
    }

    public void setjTextFieldPrecoProduto(JTextField jTextFieldPrecoProduto) {
        this.jTextFieldPrecoProduto = jTextFieldPrecoProduto;
    }

    public JTextField getjTextFieldidProduto() {
        return jTextFieldidProduto;
    }

    public void setjTextFieldidProduto(JTextField jTextFieldidProduto) {
        this.jTextFieldidProduto = jTextFieldidProduto;
    }

    public JButton getjButtonAlterarProd() {
        return jButtonAlterarProd;
    }

    public void setjButtonAlterarProd(JButton jButtonAlterarProd) {
        this.jButtonAlterarProd = jButtonAlterarProd;
    }

    public JButton getjButtonCadastrarProd() {
        return jButtonCadastrarProd;
    }

    public void setjButtonCadastrarProd(JButton jButtonCadastrarProd) {
        this.jButtonCadastrarProd = jButtonCadastrarProd;
    }

    public JButton getjButtonExcluirProd() {
        return jButtonExcluirProd;
    }

    public void setjButtonExcluirProd(JButton jButtonExcluirProd) {
        this.jButtonExcluirProd = jButtonExcluirProd;
    }

    public JButton getjButtonLimparCampos() {
        return jButtonLimparCampos;
    }

    public void setjButtonLimparCampos(JButton jButtonLimparCampos) {
        this.jButtonLimparCampos = jButtonLimparCampos;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelid = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldidProduto = new javax.swing.JTextField();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldPrecoProduto = new javax.swing.JTextField();
        jButtonCadastrarProd = new javax.swing.JButton();
        jButtonExcluirProd = new javax.swing.JButton();
        jButtonAlterarProd = new javax.swing.JButton();
        jTextFieldPesquisarProd = new javax.swing.JTextField();
        jLabelPesquisar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonLimparCampos = new javax.swing.JButton();
        jLabelTelaFundo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Produto");
        setMaximumSize(new java.awt.Dimension(796, 449));
        setMinimumSize(new java.awt.Dimension(796, 449));
        setPreferredSize(new java.awt.Dimension(796, 449));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelid.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelid.setText("*ID");
        getContentPane().add(jLabelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 30, -1));

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelNome.setText("*Nome");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabelPreco.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelPreco.setText("*Preço");
        getContentPane().add(jLabelPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jTextFieldidProduto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextFieldidProduto.setToolTipText("ID do produto");
        jTextFieldidProduto.setEnabled(false);
        jTextFieldidProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldidProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, -1));

        jTextFieldNomeProduto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextFieldNomeProduto.setToolTipText("Nome do produto");
        jTextFieldNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        jTextFieldPrecoProduto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextFieldPrecoProduto.setToolTipText("Preço do produto");
        jTextFieldPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPrecoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 30));

        jButtonCadastrarProd.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonCadastrarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconAdd.png"))); // NOI18N
        jButtonCadastrarProd.setToolTipText("Adicionar Produto");
        jButtonCadastrarProd.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonCadastrarProd.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonCadastrarProd.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonCadastrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProdActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 80));

        jButtonExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconRemover.png"))); // NOI18N
        jButtonExcluirProd.setToolTipText("Remover Produto");
        jButtonExcluirProd.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonExcluirProd.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProdActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jButtonAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconAtualizar.png"))); // NOI18N
        jButtonAlterarProd.setToolTipText("Atualizar produto");
        jButtonAlterarProd.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonAlterarProd.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonAlterarProd.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProdActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jTextFieldPesquisarProd.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextFieldPesquisarProd.setToolTipText("Nome do produto");
        jTextFieldPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarProdActionPerformed(evt);
            }
        });
        jTextFieldPesquisarProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarProdKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 140, -1));

        jLabelPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconPesquisa.png"))); // NOI18N
        getContentPane().add(jLabelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jTableProdutos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preco"
            }
        ));
        jTableProdutos.setToolTipText("Tabela dos produtos cadastrados");
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProdutos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 340, 230));

        jButtonLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/limparCampos.png"))); // NOI18N
        jButtonLimparCampos.setToolTipText("Limpar Campos");
        jButtonLimparCampos.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCamposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabelTelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/telaDeFundoProduto.jpg"))); // NOI18N
        getContentPane().add(jLabelTelaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 780, 450));

        setBounds(0, 0, 796, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProdutoActionPerformed

    private void jTextFieldidProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidProdutoActionPerformed

    private void jButtonCadastrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProdActionPerformed
        controller.salvaProduto();
    }//GEN-LAST:event_jButtonCadastrarProdActionPerformed

    private void jButtonAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProdActionPerformed
        controller.alteraDadosProduto();
    }//GEN-LAST:event_jButtonAlterarProdActionPerformed

    private void jButtonExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProdActionPerformed
       controller.deletaDadosProduto();
    }//GEN-LAST:event_jButtonExcluirProdActionPerformed

    private void jTextFieldPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoProdutoActionPerformed

    private void jTextFieldPesquisarProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarProdKeyReleased
        try {
            controller.mostraProduto();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldPesquisarProdKeyReleased

    private void jTextFieldPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarProdActionPerformed
        
    }//GEN-LAST:event_jTextFieldPesquisarProdActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
       controller.setarCamposTabelaProduto();
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void jButtonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposActionPerformed
        controller.limparCampos();
        getjButtonCadastrarProd().setEnabled(true);
    }//GEN-LAST:event_jButtonLimparCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarProd;
    private javax.swing.JButton jButtonCadastrarProd;
    private javax.swing.JButton jButtonExcluirProd;
    private javax.swing.JButton jButtonLimparCampos;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTelaFundo;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldPesquisarProd;
    private javax.swing.JTextField jTextFieldPrecoProduto;
    private javax.swing.JTextField jTextFieldidProduto;
    // End of variables declaration//GEN-END:variables
}
