-- MySQL Script generated by MySQL Workbench
-- Thu Dec 15 21:32:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemaPadaria_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemaPadaria_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemaPadaria_db` DEFAULT CHARACTER SET utf8 ;
USE `sistemaPadaria_db` ;

-- -----------------------------------------------------
-- Table `sistemaPadaria_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaPadaria_db`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `loginUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(40) NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `cargoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaPadaria_db`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaPadaria_db`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `precoDoProduto` DOUBLE NOT NULL,
  `nomeDoProduto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaPadaria_db`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaPadaria_db`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `cpfCliente` VARCHAR(15) NOT NULL,
  `ruaEndCliente` VARCHAR(100) NOT NULL,
  `bairroEndCliente` VARCHAR(45) NOT NULL,
  `numeroEndCliente` INT NOT NULL,
  `telefoneCliente` VARCHAR(15) NOT NULL,
  `celularCliente` VARCHAR(15) NULL,
  `referenciaEndCliente` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemaPadaria_db`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaPadaria_db`.`Pedido` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `dataEHorarioDoPedido` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) ,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `sistemaPadaria_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ---------------------------------------------------
-- Table `sistemaPadaria_db`.`ProdutosPedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemaPadaria_db`.`ProdutosPedidos` (
  `idProdutosPedidos` INT NOT NULL AUTO_INCREMENT,
  `itemPedido` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `preco` DOUBLE NULL,
  `statusPedido` VARCHAR(45) NULL,
  `precoTotal` DOUBLE NULL,
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedidos` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idProdutosPedidos`, `Produto_idProduto`, `Pedido_idPedidos`, `Pedido_Cliente_idCliente`),
  INDEX `fk_ProdutosPedidos_Produto1_idx` (`Produto_idProduto` ASC) ,
  INDEX `fk_ProdutosPedidos_Pedido1_idx` (`Pedido_idPedidos` ASC, `Pedido_Cliente_idCliente` ASC),
  CONSTRAINT `fk_ProdutosPedidos_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `sistemaPadaria_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProdutosPedidos_Pedido1`
    FOREIGN KEY (`Pedido_idPedidos` , `Pedido_Cliente_idCliente`)
    REFERENCES `sistemaPadaria_db`.`Pedido` (`idPedidos` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
